language: node_js
node_js: stable
install:
- yarn
script:
- hexo cl
- hexo g && gulp
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
after_script:
- cd ./public
- git init
- git add .
- git commit -m "update"
- git push --force --quiet "https://${blog}@${GH_REF}" master:master
git:
  submodules: false
before_install:
- git config user.name "olsonaolson"
- git config user.email "olsonaolson@gmail.com"
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
branches:
  only:
  - source
env:
  global:
  - GH_REF: github.com/51lucky/51lucky.github.io.git
dd:
- openssl aes-256-cbc -K $encrypted_51a4b960a013_key -iv $encrypted_51a4b960a013_iv
  -in travis.key.enc -out travis.key -d
